### ISSUE TITLE
Incorrect message dispayed while in the Crown of Sorrow raid.

### ISSUE THREAD

**Issue by TalenTaylor** [brakacai/discord-ghost#23]
The activity line reads "Grow [weak] from [pride]." instead of "Crown of Sorrow"

**Comment by louis-bompart** [comment]
I'll get a look! Thanks for your report!
@all-contributors give a cookie to @TalenTaylor for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @TalenTaylor for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @TalenTaylor for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @TalenTaylor for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @TalenTaylor for bugs
Sorry for the spam!

**Comment by louis-bompart** [comment]
Should be addressed by #67. Please try 1.2.0 https://github.com/brakacai/discord-ghost/releases/latest
![image](https://user-images.githubusercontent.com/12366410/60783547-22b43300-a119-11e9-912a-bcc469702e2e.png)
