### ISSUE TITLE
Wrong Gamemode in Crucible

### ISSUE THREAD

**Issue by ghost** [brakacai/discord-ghost#26]
Went into a Crucible match, Discord shows "Rumble" when it's Control. Map and time elapsed are correct. https://i.imgur.com/tXqINKB.png

**Comment by louis-bompart** [comment]
Will look into it thanks!
@all-contributors please add @CaptainKoby  for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @CaptainKoby for bugs

**Comment by louis-bompart** [comment]
@all-contributors please add @CaptainKoby for bugs
One last time!

**Comment by louis-bompart** [comment]
Should be addressed by #67. Please try 1.2.0 https://github.com/brakacai/discord-ghost/releases/latest
