### ISSUE TITLE
Shows as in orbit when the game isnt running

### ISSUE THREAD

**Issue by ghost** [brakacai/discord-ghost#31]
I started it up without the game running and it says I've been in orbit for 14 hours.

**Comment by louis-bompart** [comment]
Yeah we know about it, that's Bungie data not being purged. nothing we can really do, sorry :/

**Comment by ghost** [comment]
Have you considered checking if destiny2 is running before setting the status?  If the game isn't up there isnt any point in asking the API where the user is.

https://stackoverflow.com/questions/38033127/node-js-how-to-check-a-process-is-running-by-the-process-name
