### ISSUE TITLE
Config file for apikey/battletag?

### ISSUE THREAD

**Issue by ghost** [brakacai/discord-ghost#32]
These values will change very infrequently.  Can we save them to a config file so it's just a button press to start it up?

**Comment by pjuhel** [comment]
On the first launch, a config file is created in the following directory :  C:/Users/yourusername/discord-ghost

It contains your player id and your api key.

After this initial launch, your config is read from this file which you can edit at will :)

**Comment by ghost** [comment]
sweet. Thanks!
