### ISSUE TITLE
Not updating from In Orbit when in other gamemodes

### ISSUE THREAD

**Issue by okaythx** [brakacai/discord-ghost#39]
Whenever I launch anywhere the rich presence doesn't update. For example, when launching into  crucible, it stayed as saying I was in orbit. 
Log:
`(node:23556) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'characterActivities' of undefined
    at Client.getCurrentCharacterId (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Client.<anonymous> (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:23556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:23556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by okaythx** [comment]
I've tried launching the program before Destiny, and after to no avail.

**Comment by louis-bompart** [comment]
Hey @nathangamz , try to launch the app after you've selected your character.

**Comment by okaythx** [comment]
It still doesn't update

**Comment by louis-bompart** [comment]
What's your BattleTag?
Also, try to delete your settings. they're located in `C:/Users/UR_USERNAME/discord-ghost` and reconfigure the app, take extra care when you'll type your stuff

**Comment by okaythx** [comment]
My BattleTag is NathanGamz#1352

**Comment by okaythx** [comment]
I've also reconfigured the settings and it still shows up as me being in orbit when in reality I'm in the Dreaming City, for example

**Comment by okaythx** [comment]
Alright, downloading the latest version of the app worked. Thanks though!

**Comment by louis-bompart** [comment]
Oh I should have asked that first! Sorry!
