### ISSUE TITLE
Incorrect message while at the Tower

### ISSUE THREAD

**Issue by ghost** [brakacai/discord-ghost#41]
Instead of displaying The Last City, "Home of the Guardians, where you can regroup, rearm, and form new allian..." appears.

![image](https://user-images.githubusercontent.com/50473815/60690203-71e93200-9e93-11e9-8925-444a8a84b9a4.png)

**Comment by pjuhel** [comment]
Hello ! Thanks for your feedback. 
" The Last City " should be displayed when hovering you mouse over the picture, is that working as intended ? Regarding the description, i see why you would expect to see The Last City listed right under a Social tag, rather than the ubiquitous description. We'll see if we can improve this aspect !

**Comment by ghost** [comment]
Yes, The Last City appears on hover.

**Comment by ghost** [comment]
for me it shows my current activity hash is 
`"currentActivityHash": 3903562779`

That translates to this in the API:

```
"3903562779": {
    "displayProperties": {
      "description": "Home of the Guardians, where you can regroup, rearm, and form new alliances before venturing beyond.",
      "name": "Tower",
      "icon": "/common/destiny2_content/icons/0fa52de77ac582dd8d1ce976c32bfb5b.png",
      "hasIcon": true
    },
```

They're using the description of the area.

Suggestion -   

change the text to [name] - [description].  then when bungie's description is not intuitive like this, the user will know where the person is without having to hover over the picture.  I don't think you can hover over the picture on a phone so all a user would have to go on is the description in that case.

**Comment by pjuhel** [comment]
Thanks Akumati, this is indeed close to what i had in mind ! 

I will try to handle separately the display on social space in a first place, as such long description isn't particularly helpful.

**Comment by louis-bompart** [comment]
We'll need to aggregate multiple "quirky" display so we can find how to hit the nail in one fell swoop.
