### ISSUE TITLE
Show incorrect game mode when in pvp

### ISSUE THREAD

**Issue by Tacoriffic11** [brakacai/discord-ghost#47]
When you go into quickplay and get into a match on discord it shows that you are doing rumble instead of quickplay. 
![Discord_2019-07-04_20-16-44](https://user-images.githubusercontent.com/16025245/60692152-2f772380-9e9a-11e9-8d2b-7fe41547d7fd.png)

**Comment by louis-bompart** [comment]
Thank you for your report we are aware of the issue and are working on it!

**Comment by louis-bompart** [comment]
DEV Note: relates to #23

**Comment by louis-bompart** [comment]
Should be addressed by #67. Please try 1.2.0 https://github.com/brakacai/discord-ghost/releases/latest
