### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by OxeaAU** [brakacai/discord-ghost#53]
```
Config file found
Starting service
(node:11832) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Client.getCurrentCharacterId (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Client.<anonymous> (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at Generator.next (<anonymous>)
    at fulfilled (C:\snapshot\discord-ghost\dist\Client.js:0:0)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:11832) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:11832) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I had the game running on my PS4 beforehand as instructed otherwise using this on Windows.

**Comment by louis-bompart** [comment]
Thanks for the report, also, send me your PSN ID, so I can check the Bungie API log for your profile

**Comment by louis-bompart** [comment]
-DEV Note:
Add null check on getCurrentCharactrerId on response param and its cohort.

**Comment by OxeaAU** [comment]
> Thanks for the report, also, send me your PSN ID, so I can check the Bungie API log for your profile

My PSN is the same as my GitHub name.

**Comment by louis-bompart** [comment]
Can you tell me what you're privacy settings are on bungie?
https://www.bungie.net/en/Profile/Settings?category=Privacy
Try enabling `Show my Progression (what I've completed in Destiny, and my current status)`

**Comment by OxeaAU** [comment]
![image](https://user-images.githubusercontent.com/52558402/60734096-19e52500-9f92-11e9-82ed-668996212a8f.png)

That was my privacy settings. I enabled the setting and then proceeded to run the program but now it just hangs on the 'Starting Service' part. I waited for 10 minutes before exiting the program.

**Comment by louis-bompart** [comment]
The hang in Starting Service is normal, it means the service is running properly. Checked your status, it should be updated. If not, you may want to check your discord game activity setting, you need to have `display currently running game as as status message` enabled

**Comment by louis-bompart** [comment]
#55 Long term fix will be:
