### ISSUE TITLE
Time elapsed does not reset when changing activities

### ISSUE THREAD

**Issue by Spiderman2PizzaTheme** [brakacai/discord-ghost#54]
If you're say, in orbit for 5 minutes then play some gambit when you return to orbit the time you've spent in orbit will resume from 5 minutes rather than zero. This is the same for all activities.

**Comment by pjuhel** [comment]
Thank you for your feedback. We'll look into this issue.

An update is on its way to refactor the display, we'll try to cram a fix for this in it as well !

**Comment by louis-bompart** [comment]
Should be addressed by #67. Please try 1.2.0 https://github.com/brakacai/discord-ghost/releases/latest
