### ISSUE TITLE
Add OAuth

### ISSUE THREAD

**Issue by louis-bompart** [brakacai/discord-ghost#55]
As we found out, we need either the user to have lenient privacy settings or to grant us access. The latter is the good way of doing it, but we need to introduce OAuth to do so.

**Comment by ghost** [comment]
They probably need their activity feed enabled.  OAUTH was a fun one for me to get working.  not sure if you can do that without an https website for bungie to send the code to.

https://www.bungie.net/en/Profile/Settings?category=Privacy - enable activity feed

**Comment by louis-bompart** [comment]
I can redirect to localhost and run an https server that listen to the it.
It works fine I tried it ;)

**Comment by louis-bompart** [comment]
I have to give a mandatory update on this, I oversight the security side of it. I cannot certify localhost leading to chrome freaking out. So to fix it, I'll use custom protocol with electron.

**Comment by louis-bompart** [comment]
Done! @Akumati1435 the trick to make it works without https website was to use custom-protocol, but heck, it was surely one of the hardest things I have done on the project.

There's also bungie-net/api#961 that came from this.
Learned quite a lot from this one.
