### ISSUE TITLE
Discord-Ghost will not display regardless of what I do.

### ISSUE THREAD

**Issue by Cloud557** [brakacai/discord-ghost#66]
I saw the program on Reddit and thought that would be a fun way to have my buddies know when I'm playing D2 and what I'm doing while I'm playing so they can decide if they want to hop in and join me or not. 

However, after trying several times, on two different PC's (Both at the same time and alone), it just will not display in my profile at all. After sitting with the program open for a little while (Roughly 30-60 minutes) I get the attached error message in the CMD window.

I am playing on PS4 if that matters, but either way, here is the error I keep getting (I get this error on both PC's, but this one is taken from my Laptop since it was active there first)

![Destiny Discord Error](https://user-images.githubusercontent.com/2002819/60772417-09cd6280-a0c4-11e9-8dd3-bfe13704a270.png)

**Comment by louis-bompart** [comment]
Thanks for reaching out, did you set your privacy settings on Bungie.net?

**Comment by Cloud557** [comment]
Yes I did. It is public. I also had this issue while it was private and that's why I changed it to public, where I am still having this issue.

**Comment by louis-bompart** [comment]
Going by the assumption that your GitHub username is the same as your PSN one, I see that you have your Xbox linked to your Bungie account. This relates to #65 

As a workaround, try to do this:
Open your config.json file (Located in `C:/Users/yourname/discord-ghost`)
Change platform to 2
Change playerId to "4611686018437855145"

**Comment by Cloud557** [comment]
I don't even own an Xbox... There's some guy on XBL that has the GT CLOUD557 and I have no way of changing that or making him change that...

**Comment by louis-bompart** [comment]
Feels bad man :( But does this fix your issue? 
We're aiming to fix that better with authentication with Bungie, from there, it'll be much smoother!

**Comment by louis-bompart** [comment]
@Cloud557, did you manage to make it work in the end?

**Comment by louis-bompart** [comment]
Close because inactive. Reopen/response if needed
