### ISSUE TITLE
Convert to Electron

### ISSUE THREAD

**Issue by louis-bompart** [brakacai/discord-ghost#72]
I really, really, really didn't want that. But, this is a need for OAuth.

For OAuth, I need to redirect to a custom protocol. HTTP is a no-go because Bungie refuses it (and they're right). HTTPS is not a solution because I cannot provide a signed localhost certificate (and it won't be secure). Thus, I need to use a custom protocol. `discord-ghost://` surely.

The internets all leads to Electron, thus my despair. I welcome all suggestions on this one.

**Comment by greavettey** [comment]
I can help if I get some free time. I love electron.

**Comment by louis-bompart** [comment]
Thanks! I completed the conversion already (i.e. just being able to run the app).
I still need to update our CI to switch from pkg to electron and then it'll be mostly done.

It'll be running on a separate branch till v2 is complete in it and then it'll join master as a breaking release (so 2.0.0).

They should not be any UI, per design: We only need to OAuth login the user and from there we can find out his character. 

The notification tray cross platform is something that I'll be glad to have help on, so I can focus on the new 'service' way of thing (i.e. detecting when the game's start on pc etc)

**Comment by louis-bompart** [comment]
@axelgreavette if your expertise with electron cover how to properly use native node modules with webpack and electron-forge, your help would be very much welcome. Right now I'm stuck because electron-forge webpack setup link keytar (a node module to securely keep user secrets on their OS secrets lockbox) to the absolute path of the .node file on build, which ofc won't work once you try to install it.

**Comment by louis-bompart** [comment]
Completed
