### ISSUE TITLE
Activity timer does not reset when switching activities

### ISSUE THREAD

**Issue by Randactyl** [brakacai/discord-ghost#81]
Not quite the same as #54

Noticed this while I was farming up some data lettuce. The time elapsed when switching from the activity to the orbit queue continues on from the activity.
![activity to orbit gif](https://user-images.githubusercontent.com/1325428/61174633-dbce9f00-a557-11e9-89ac-1b63bbf0333e.gif)

The timer does restart when the next activity loads.
![orbit to activity gif](https://user-images.githubusercontent.com/1325428/61174636-e852f780-a557-11e9-8cc2-ed8413badae1.gif)

I haven't tested activities other than forges or if manually going to orbit behaves differently. Perhaps it is only forges due to their usually very short queue time or because they have some other unique behavior (you can't orbit straight from the activity - your option is "Abandon Activity" like a patrol or adventure iirc).

Sorry for the drive-by issue, just wanted to log it before I got busy today and forgot!

**Comment by louis-bompart** [comment]
Just to be sure: you're on a forge activity, the activity ends up and you are sent back in the matchmaking/orbit but the timer is not reset. However, when your next forge round start, the timer is a-ok?

**Comment by Randactyl** [comment]
that is correct

**Comment by louis-bompart** [comment]
Should be fixed in v2, it's kinda related to bungie-net/api#981 also, so out of our hand
