### ISSUE TITLE
Newest release doesn't work

### ISSUE THREAD

**Issue by stayupthetree** [brakacai/discord-ghost#97]
It errors, looking for stuff under user Travis

**Comment by louis-bompart** [comment]
Yeah I know, I tagged all 2.x as pre-release for this reason. You have
certainly noticed that the switch to Electron ain't butter smooth.

Le mar. 16 juil. 2019 à 12:45, stayupthetree <notifications@github.com> a
écrit :

**Comment by louis-bompart** [comment]
From my test, the version that's being built (2.0.7) should works it's cringy cause of the window that you have to let open, but I'll investigate the system tray and sync pause resume another day. (baby steps! and a lot of rest)

**Comment by louis-bompart** [comment]
Close because it's fixed. Release post in writing
